# Generated by Django 3.2.9 on 2021-11-28 03:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255, unique=True)),
                ('debts', models.ManyToManyField(to='splitwise.Debt')),
                ('members', models.ManyToManyField(to='splitwise.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FriendGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balances', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='splitwise.balance')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paid_share', models.IntegerField(default=0)),
                ('owed_share', models.IntegerField(default=0)),
                ('net_balance', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitwise.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='debt',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='splitwise.userprofile'),
        ),
        migrations.AddField(
            model_name='debt',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='splitwise.userprofile'),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splitwise.userprofile')),
                ('balances', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='splitwise.balance')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='splitwise.group')),
            ],
            options={
                'abstract': False,
            },
            bases=('splitwise.userprofile',),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('description', models.CharField(max_length=255)),
                ('payment', models.BooleanField(default=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='splitwise.group')),
                ('repayments', models.ManyToManyField(to='splitwise.Debt')),
                ('users', models.ManyToManyField(to='splitwise.ExpenseUser')),
                ('friendship_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='splitwise.friend')),
            ],
        ),
    ]
