# Generated by Django 3.2.9 on 2021-11-28 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='group_id',
            new_name='group',
        ),
    ]
