# Generated by Django 3.2.9 on 2021-11-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0002_rename_group_id_expense_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='debts',
            field=models.ManyToManyField(null=True, to='splitwise.Debt'),
        ),
    ]
