# Generated by Django 3.2.9 on 2021-11-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0003_alter_group_debts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendgroup',
            name='balances',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='friendship_id',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='FriendGroup',
        ),
    ]
