# Generated by Django 3.2.9 on 2021-11-28 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0005_auto_20211128_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_group',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='splitwise.group'),
        ),
    ]
